url: $DB_URL
username: $DB_USERNAME
password: $DB_PASSWORD
classpath: /liquibase/changelog
changeLogFile: root-changelog.xml
driver: shaded.liquibase.ru.yandex.clickhouse.ClickHouseDriver
databaseClass: liquibase.ext.clickhouse.database.ClickHouseDatabase
strict: true
changelogLockPollRate: 5